// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unehnuoczenmcyqmvsvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZWhudW9jemVubWN5cW12c3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjEyMDAsImV4cCI6MjA2NTEzNzIwMH0.jA4ftRwehwfMcI6Vuw92MAwBhK85Kgs51YrtH4Oz5e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);